/*
 * YKS – AYT (Alan Yeterlilik Testleri) ve YDT (Yabancı Dil Testi) konu listesi.
 *
 * Kaynaklar (erişim: 2026-10-04):
 * - ÖSYM YKS test yapısı (AYT: Matematik 40, Fen 40, Türk Dili ve Edebiyatı–Sosyal Bilimler-1 40
 *   [Edebiyat 24, Tarih-1 10, Coğrafya-1 6], Sosyal Bilimler-2 40 [Tarih-2 11, Coğrafya-2 11,
 *   Felsefe Grubu 12, Din 6]; YDT 80): https://www.osym.gov.tr/ (dağılım ikincil kaynaklardan).
 * - MEB OGM, Maarif Modeli geçişi (2026-2027'de 9-11 yeni program, 12. sınıf önceki program):
 *   https://ogm.meb.gov.tr/www/2026-2027-egitim-ogretim-yili-turkiye-yuzyili-maarif-modeli-taslak-cerceve-planlar-yayimlandi/icerik/2633/tr
 * - Yaygın konu listeleri (karşılaştırma için):
 *   https://www.kitapsec.com/blog/ayt-konulari-ve-soru-dagilimi-235.html
 *   https://www.bilgenc.com/ayt-tarih-1-konulari/
 *   https://www.rehberimsensin.com/ayt-cografya-konulari-ve-soru-dagilimi
 *   https://www.xyzakademi.com.tr/ayt-felsefe-konulari/
 *   https://krakademi.com/blog-detay/2026-ayt-edebiyat-konulari-ve-soru-dagilimi-2035
 *
 * Belirsizlik notları:
 * - YKS 2027 adayları önceki (2018 tabanlı) ortaöğretim programlarıyla okudu; liste buna göredir.
 *   Maarif Modeli'ne göre ilk YKS'nin 2028 olması bekleniyor; o zaman kapsam değişebilir.
 * - AYT pratikte 9-12. sınıfların tümünü kapsar; burada TYT'de olmayan/AYT'ye özgü başlıklar
 *   ağırlıklıdır. Tarih ve Coğrafya, Tarih-1/Tarih-2 ve Coğrafya-1/Coğrafya-2 testlerinin birleşik
 *   listesidir (öğrencinin alanına göre bir kısmı sorulmaz).
 * - YDT konu başlıkları ÖSYM soru tiplerine göre düzenlendi; dile göre (İngilizce/Almanca/Arapça/
 *   Fransızca/Rusça) değişmez.
 */
import type { SubjectTopics } from './types';

export const AYT_TOPICS: SubjectTopics = {
  matematik: [
    { id: 'ayt.matematik.fonksiyonlar', name: 'Fonksiyonlar' },
    { id: 'ayt.matematik.polinomlar', name: 'Polinomlar' },
    { id: 'ayt.matematik.ikinci-derece-denklemler', name: '2. Dereceden Denklemler' },
    { id: 'ayt.matematik.karmasik-sayilar', name: 'Karmaşık Sayılar' },
    { id: 'ayt.matematik.parabol', name: 'Parabol' },
    { id: 'ayt.matematik.esitsizlikler', name: 'Eşitsizlikler' },
    { id: 'ayt.matematik.permutasyon', name: 'Permütasyon' },
    { id: 'ayt.matematik.kombinasyon', name: 'Kombinasyon' },
    { id: 'ayt.matematik.binom', name: 'Binom' },
    { id: 'ayt.matematik.olasilik', name: 'Olasılık' },
    { id: 'ayt.matematik.trigonometri-1', name: 'Trigonometri – 1 (Trigonometrik Oranlar ve Birim Çember)' },
    { id: 'ayt.matematik.trigonometri-2', name: 'Trigonometri – 2 (Toplam-Fark ve Dönüşüm Formülleri)' },
    { id: 'ayt.matematik.trigonometrik-denklemler', name: 'Trigonometrik Denklemler' },
    { id: 'ayt.matematik.ustel-fonksiyonlar', name: 'Üstel Fonksiyonlar' },
    { id: 'ayt.matematik.logaritma', name: 'Logaritma' },
    { id: 'ayt.matematik.diziler', name: 'Diziler' },
    { id: 'ayt.matematik.limit-sureklilik', name: 'Limit ve Süreklilik' },
    { id: 'ayt.matematik.turev', name: 'Türev' },
    { id: 'ayt.matematik.turev-uygulamalari', name: 'Türevin Uygulamaları' },
    { id: 'ayt.matematik.belirsiz-integral', name: 'Belirsiz İntegral' },
    { id: 'ayt.matematik.belirli-integral', name: 'Belirli İntegral ve Alan' },
  ],
  geometri: [
    { id: 'ayt.geometri.ucgenler', name: 'Üçgenler (Açı, Benzerlik, Alan)' },
    { id: 'ayt.geometri.cokgenler', name: 'Çokgenler' },
    { id: 'ayt.geometri.dortgenler', name: 'Dörtgenler' },
    { id: 'ayt.geometri.yamuk', name: 'Yamuk' },
    { id: 'ayt.geometri.paralelkenar', name: 'Paralelkenar' },
    { id: 'ayt.geometri.eskenar-dortgen-deltoid', name: 'Eşkenar Dörtgen ve Deltoid' },
    { id: 'ayt.geometri.dikdortgen-kare', name: 'Dikdörtgen ve Kare' },
    { id: 'ayt.geometri.cemberde-aci', name: 'Çemberde Açı' },
    { id: 'ayt.geometri.cemberde-uzunluk', name: 'Çemberde Uzunluk' },
    { id: 'ayt.geometri.dairede-alan', name: 'Daire ve Dairede Alan' },
    { id: 'ayt.geometri.noktanin-analitigi', name: 'Noktanın Analitik İncelenmesi' },
    { id: 'ayt.geometri.dogrunun-analitigi', name: 'Doğrunun Analitik İncelenmesi' },
    { id: 'ayt.geometri.donusum-geometrisi', name: 'Dönüşüm Geometrisi' },
    { id: 'ayt.geometri.cemberin-analitigi', name: 'Çemberin Analitik İncelenmesi' },
    { id: 'ayt.geometri.kati-cisimler', name: 'Katı Cisimler' },
  ],
  fizik: [
    { id: 'ayt.fizik.vektorler', name: 'Vektörler' },
    { id: 'ayt.fizik.bagil-hareket', name: 'Bağıl Hareket' },
    { id: 'ayt.fizik.newton-yasalari', name: 'Newton’un Hareket Yasaları' },
    { id: 'ayt.fizik.sabit-ivmeli-hareket', name: 'Bir Boyutta Sabit İvmeli Hareket' },
    { id: 'ayt.fizik.atislar', name: 'İki Boyutta Hareket (Atışlar)' },
    { id: 'ayt.fizik.enerji-ve-hareket', name: 'Enerji ve Hareket' },
    { id: 'ayt.fizik.itme-momentum', name: 'İtme ve Çizgisel Momentum' },
    { id: 'ayt.fizik.tork-denge', name: 'Tork ve Denge' },
    { id: 'ayt.fizik.kutle-merkezi', name: 'Kütle Merkezi' },
    { id: 'ayt.fizik.basit-makineler', name: 'Basit Makineler' },
    { id: 'ayt.fizik.elektrik-alan-potansiyel', name: 'Elektriksel Kuvvet, Alan ve Potansiyel' },
    { id: 'ayt.fizik.sigaclar', name: 'Düzgün Elektrik Alan ve Sığa' },
    { id: 'ayt.fizik.manyetizma-induksiyon', name: 'Manyetizma ve Elektromanyetik İndüklenme' },
    { id: 'ayt.fizik.alternatif-akim', name: 'Alternatif Akım ve Transformatörler' },
    { id: 'ayt.fizik.cembersel-hareket', name: 'Çembersel Hareket' },
    { id: 'ayt.fizik.basit-harmonik-hareket', name: 'Basit Harmonik Hareket' },
    { id: 'ayt.fizik.dalga-mekanigi', name: 'Dalga Mekaniği' },
    { id: 'ayt.fizik.atom-fizigi', name: 'Atom Fiziğine Giriş ve Radyoaktivite' },
    { id: 'ayt.fizik.modern-fizik', name: 'Modern Fizik' },
    { id: 'ayt.fizik.modern-fizik-uygulamalari', name: 'Modern Fiziğin Teknolojideki Uygulamaları' },
  ],
  kimya: [
    { id: 'ayt.kimya.modern-atom-teorisi', name: 'Modern Atom Teorisi' },
    { id: 'ayt.kimya.gazlar', name: 'Gazlar' },
    { id: 'ayt.kimya.sivi-cozeltiler', name: 'Sıvı Çözeltiler ve Çözünürlük' },
    { id: 'ayt.kimya.tepkimelerde-enerji', name: 'Kimyasal Tepkimelerde Enerji' },
    { id: 'ayt.kimya.tepkimelerde-hiz', name: 'Kimyasal Tepkimelerde Hız' },
    { id: 'ayt.kimya.kimyasal-denge', name: 'Kimyasal Tepkimelerde Denge' },
    { id: 'ayt.kimya.asit-baz-dengesi', name: 'Asit-Baz Dengesi' },
    { id: 'ayt.kimya.cozunurluk-dengesi', name: 'Çözünürlük Dengesi' },
    { id: 'ayt.kimya.kimya-ve-elektrik', name: 'Kimya ve Elektrik' },
    { id: 'ayt.kimya.karbon-kimyasi', name: 'Karbon Kimyasına Giriş' },
    { id: 'ayt.kimya.organik-bilesikler', name: 'Organik Bileşikler' },
    { id: 'ayt.kimya.enerji-kaynaklari', name: 'Enerji Kaynakları ve Bilimsel Gelişmeler' },
  ],
  biyoloji: [
    { id: 'ayt.biyoloji.sinir-sistemi', name: 'Sinir Sistemi' },
    { id: 'ayt.biyoloji.endokrin-sistem', name: 'Endokrin Sistem' },
    { id: 'ayt.biyoloji.duyu-organlari', name: 'Duyu Organları' },
    { id: 'ayt.biyoloji.destek-hareket', name: 'Destek ve Hareket Sistemi' },
    { id: 'ayt.biyoloji.sindirim-sistemi', name: 'Sindirim Sistemi' },
    { id: 'ayt.biyoloji.dolasim-bagisiklik', name: 'Dolaşım ve Bağışıklık Sistemi' },
    { id: 'ayt.biyoloji.solunum-sistemi', name: 'Solunum Sistemi' },
    { id: 'ayt.biyoloji.bosaltim-sistemi', name: 'Üriner (Boşaltım) Sistem' },
    { id: 'ayt.biyoloji.ureme-sistemi', name: 'Üreme Sistemi ve Embriyonik Gelişim' },
    { id: 'ayt.biyoloji.komunite-populasyon', name: 'Komünite ve Popülasyon Ekolojisi' },
    { id: 'ayt.biyoloji.genden-proteine', name: 'Nükleik Asitler ve Genden Proteine' },
    { id: 'ayt.biyoloji.fotosentez-kemosentez', name: 'Fotosentez ve Kemosentez' },
    { id: 'ayt.biyoloji.hucresel-solunum', name: 'Hücresel Solunum' },
    { id: 'ayt.biyoloji.bitki-biyolojisi', name: 'Bitki Biyolojisi' },
    { id: 'ayt.biyoloji.canlilar-ve-cevre', name: 'Canlılar ve Çevre' },
  ],
  edebiyat: [
    { id: 'ayt.edebiyat.anlam-bilgisi', name: 'Anlam Bilgisi (Sözcük, Cümle, Paragraf)' },
    { id: 'ayt.edebiyat.dil-bilgisi', name: 'Dil Bilgisi' },
    { id: 'ayt.edebiyat.siir-bilgisi', name: 'Şiir Bilgisi (Nazım Birimi, Ölçü, Uyak, Redif)' },
    { id: 'ayt.edebiyat.soz-sanatlari', name: 'Söz Sanatları' },
    { id: 'ayt.edebiyat.metin-turleri', name: 'Metinlerin Sınıflandırılması' },
    { id: 'ayt.edebiyat.hikaye-roman', name: 'Hikâye ve Roman' },
    { id: 'ayt.edebiyat.tiyatro', name: 'Tiyatro' },
    { id: 'ayt.edebiyat.ogretici-metinler', name: 'Öğretici Metinler (Makale, Deneme, Fıkra, Eleştiri vb.)' },
    { id: 'ayt.edebiyat.anlatmaya-bagli-turler', name: 'Destan, Efsane, Masal ve Halk Hikâyesi' },
    { id: 'ayt.edebiyat.donemler', name: 'Türk Edebiyatının Dönemleri' },
    { id: 'ayt.edebiyat.islamiyet-oncesi', name: 'İslamiyet Öncesi Türk Edebiyatı' },
    { id: 'ayt.edebiyat.gecis-donemi', name: 'Geçiş Dönemi Türk Edebiyatı' },
    { id: 'ayt.edebiyat.anonim-halk', name: 'Halk Edebiyatı: Anonim Halk Edebiyatı' },
    { id: 'ayt.edebiyat.asik-edebiyati', name: 'Halk Edebiyatı: Âşık Edebiyatı' },
    { id: 'ayt.edebiyat.tekke-tasavvuf', name: 'Halk Edebiyatı: Dini-Tasavvufi Halk Edebiyatı' },
    { id: 'ayt.edebiyat.divan-nazim', name: 'Divan Edebiyatı: Nazım Biçimleri ve Türleri' },
    { id: 'ayt.edebiyat.divan-sanatcilari', name: 'Divan Edebiyatı: Şairler ve Eserler' },
    { id: 'ayt.edebiyat.divan-nesri', name: 'Divan Nesri' },
    { id: 'ayt.edebiyat.tanzimat-1', name: 'Tanzimat Edebiyatı 1. Dönem' },
    { id: 'ayt.edebiyat.tanzimat-2', name: 'Tanzimat Edebiyatı 2. Dönem' },
    { id: 'ayt.edebiyat.servet-i-funun', name: 'Servet-i Fünun Edebiyatı' },
    { id: 'ayt.edebiyat.fecr-i-ati', name: 'Fecr-i Âti Edebiyatı' },
    { id: 'ayt.edebiyat.milli-edebiyat', name: 'Millî Edebiyat Dönemi' },
    { id: 'ayt.edebiyat.cumhuriyet-siir-1923-1940', name: 'Cumhuriyet Dönemi Şiiri (1923-1940)' },
    { id: 'ayt.edebiyat.garip-ve-bagimsizlar', name: 'Garip Hareketi ve Bağımsız Şairler' },
    { id: 'ayt.edebiyat.ikinci-yeni', name: 'İkinci Yeni Şiiri' },
    { id: 'ayt.edebiyat.toplumcu-siir', name: 'Toplumcu Gerçekçi Şiir' },
    { id: 'ayt.edebiyat.milli-dini-duyarlilik', name: 'Millî ve Dinî Duyarlılığı Yansıtan Şiir' },
    { id: 'ayt.edebiyat.cumhuriyet-roman-hikaye', name: 'Cumhuriyet Dönemi Roman ve Hikâye' },
    { id: 'ayt.edebiyat.cumhuriyet-tiyatro', name: 'Cumhuriyet Dönemi Tiyatro' },
    { id: 'ayt.edebiyat.edebi-akimlar', name: 'Edebî Akımlar' },
    { id: 'ayt.edebiyat.dunya-edebiyati', name: 'Dünya Edebiyatı' },
  ],
  tarih: [
    { id: 'ayt.tarih.tarih-ve-zaman', name: 'Tarih ve Zaman' },
    { id: 'ayt.tarih.insanligin-ilk-donemleri', name: 'İnsanlığın İlk Dönemleri' },
    { id: 'ayt.tarih.orta-cagda-dunya', name: 'Orta Çağ’da Dünya' },
    { id: 'ayt.tarih.ilk-orta-cag-turk-dunyasi', name: 'İlk ve Orta Çağlarda Türk Dünyası' },
    { id: 'ayt.tarih.islam-medeniyeti', name: 'İslam Medeniyetinin Doğuşu' },
    { id: 'ayt.tarih.ilk-turk-islam-devletleri', name: 'Türklerin İslamiyet’i Kabulü ve İlk Türk-İslam Devletleri' },
    { id: 'ayt.tarih.selcuklu-turkiyesi', name: 'Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi' },
    { id: 'ayt.tarih.beylikten-devlete-osmanli', name: 'Beylikten Devlete Osmanlı Siyaseti (1302-1453)' },
    { id: 'ayt.tarih.savascilar-askerler', name: 'Devletleşme Sürecinde Savaşçılar ve Askerler' },
    { id: 'ayt.tarih.beylikten-devlete-medeniyet', name: 'Beylikten Devlete Osmanlı Medeniyeti' },
    { id: 'ayt.tarih.dunya-gucu-osmanli', name: 'Dünya Gücü Osmanlı (1453-1595)' },
    { id: 'ayt.tarih.merkez-teskilati', name: 'Sultan ve Osmanlı Merkez Teşkilatı' },
    { id: 'ayt.tarih.klasik-cag-toplum', name: 'Klasik Çağda Osmanlı Toplum Düzeni' },
    { id: 'ayt.tarih.degisen-dunya-dengeleri', name: 'Değişen Dünya Dengeleri Karşısında Osmanlı Siyaseti (1595-1774)' },
    { id: 'ayt.tarih.degisim-caginda-avrupa', name: 'Değişim Çağında Avrupa ve Osmanlı' },
    { id: 'ayt.tarih.denge-stratejisi', name: 'Uluslararası İlişkilerde Denge Stratejisi (1774-1914)' },
    { id: 'ayt.tarih.devrimler-cagi', name: 'Devrimler Çağında Değişen Devlet-Toplum İlişkileri' },
    { id: 'ayt.tarih.sermaye-ve-emek', name: 'Sermaye ve Emek' },
    { id: 'ayt.tarih.gundelik-hayat', name: '19. ve 20. Yüzyılda Değişen Gündelik Hayat' },
    { id: 'ayt.tarih.yirminci-yuzyil-osmanli', name: '20. Yüzyıl Başlarında Osmanlı Devleti ve Dünya' },
    { id: 'ayt.tarih.milli-mucadele', name: 'Millî Mücadele' },
    { id: 'ayt.tarih.ataturkculuk-inkilaplar', name: 'Atatürkçülük ve Türk İnkılabı' },
    { id: 'ayt.tarih.iki-savas-arasi', name: 'İki Savaş Arasındaki Dönemde Türkiye ve Dünya' },
    { id: 'ayt.tarih.ikinci-dunya-savasi', name: 'II. Dünya Savaşı Sürecinde Türkiye ve Dünya' },
    { id: 'ayt.tarih.soguk-savas', name: 'Soğuk Savaş Döneminde Türkiye ve Dünya' },
    { id: 'ayt.tarih.yumusama-donemi', name: 'Yumuşama Dönemi ve Sonrasında Türkiye ve Dünya' },
    { id: 'ayt.tarih.kuresellesen-dunya', name: 'Küreselleşen Dünyada Türkiye' },
  ],
  cografya: [
    { id: 'ayt.cografya.dogal-sistemler', name: 'Doğal Sistemler (Coğrafya-1 Tekrarı)' },
    { id: 'ayt.cografya.ekosistem', name: 'Ekosistem ve Biyoçeşitlilik' },
    { id: 'ayt.cografya.biyomlar', name: 'Biyomlar' },
    { id: 'ayt.cografya.enerji-akisi-madde-dongusu', name: 'Enerji Akışı ve Madde Döngüsü' },
    { id: 'ayt.cografya.nufus-politikalari', name: 'Nüfus Politikaları' },
    { id: 'ayt.cografya.turkiyede-nufus-yerlesme', name: 'Türkiye’de Nüfus ve Yerleşme' },
    { id: 'ayt.cografya.goc-sehirlesme', name: 'Göç ve Şehirleşme' },
    { id: 'ayt.cografya.ekonomik-faaliyetler', name: 'Ekonomik Faaliyetler ve Doğal Kaynaklar' },
    { id: 'ayt.cografya.turkiye-tarim-hayvancilik', name: 'Türkiye’de Tarım ve Hayvancılık' },
    { id: 'ayt.cografya.madenler-enerji', name: 'Türkiye’de Madenler ve Enerji Kaynakları' },
    { id: 'ayt.cografya.sanayi', name: 'Türkiye’de Sanayi' },
    { id: 'ayt.cografya.ulasim-ticaret-turizm', name: 'Türkiye’de Ulaşım, Ticaret ve Turizm' },
    { id: 'ayt.cografya.islevsel-bolgeler', name: 'Türkiye’nin İşlevsel Bölgeleri ve Kalkınma Projeleri' },
    { id: 'ayt.cografya.kuresel-ticaret', name: 'Küresel Ticaret' },
    { id: 'ayt.cografya.kultur-bolgeleri', name: 'İlk Kültür Merkezleri ve Kültür Bölgeleri' },
    { id: 'ayt.cografya.ulkeler', name: 'Bölgeler ve Ülkeler' },
    { id: 'ayt.cografya.jeopolitik', name: 'Jeopolitik Konum ve Çatışma Bölgeleri' },
    { id: 'ayt.cografya.kuresel-orgutler', name: 'Küresel ve Bölgesel Örgütler' },
    { id: 'ayt.cografya.cevre-sorunlari', name: 'Çevre Sorunları ve Doğal Kaynakların Sürdürülebilir Kullanımı' },
    { id: 'ayt.cografya.iklim-degisimi', name: 'Ekstrem Doğa Olayları ve Küresel İklim Değişimi' },
  ],
  felsefe: [
    { id: 'ayt.felsefe.felsefe-tanima', name: 'Felsefe: Felsefeyi Tanıma' },
    { id: 'ayt.felsefe.felsefe-bilgi', name: 'Felsefe: Bilgi Felsefesi' },
    { id: 'ayt.felsefe.felsefe-varlik', name: 'Felsefe: Varlık Felsefesi' },
    { id: 'ayt.felsefe.felsefe-ahlak', name: 'Felsefe: Ahlak Felsefesi' },
    { id: 'ayt.felsefe.felsefe-sanat', name: 'Felsefe: Sanat Felsefesi' },
    { id: 'ayt.felsefe.felsefe-din', name: 'Felsefe: Din Felsefesi' },
    { id: 'ayt.felsefe.felsefe-siyaset', name: 'Felsefe: Siyaset Felsefesi' },
    { id: 'ayt.felsefe.felsefe-bilim', name: 'Felsefe: Bilim Felsefesi' },
    { id: 'ayt.felsefe.felsefe-mo6-ms2', name: 'Felsefe: MÖ 6. Yüzyıl – MS 2. Yüzyıl Felsefesi' },
    { id: 'ayt.felsefe.felsefe-ms2-ms15', name: 'Felsefe: MS 2. Yüzyıl – MS 15. Yüzyıl Felsefesi' },
    { id: 'ayt.felsefe.felsefe-15-17', name: 'Felsefe: 15. Yüzyıl – 17. Yüzyıl Felsefesi' },
    { id: 'ayt.felsefe.felsefe-18-19', name: 'Felsefe: 18. Yüzyıl – 19. Yüzyıl Felsefesi' },
    { id: 'ayt.felsefe.felsefe-20', name: 'Felsefe: 20. Yüzyıl Felsefesi' },
    { id: 'ayt.felsefe.psikoloji-giris', name: 'Psikoloji: Psikoloji Bilimini Tanıyalım' },
    { id: 'ayt.felsefe.psikoloji-temel-surecler', name: 'Psikoloji: Psikolojinin Temel Süreçleri' },
    { id: 'ayt.felsefe.psikoloji-ogrenme', name: 'Psikoloji: Öğrenme, Bellek, Düşünme' },
    { id: 'ayt.felsefe.psikoloji-ruh-sagligi', name: 'Psikoloji: Ruh Sağlığının Temelleri' },
    { id: 'ayt.felsefe.sosyoloji-giris', name: 'Sosyoloji: Sosyolojiye Giriş' },
    { id: 'ayt.felsefe.sosyoloji-birey-toplum', name: 'Sosyoloji: Birey ve Toplum' },
    { id: 'ayt.felsefe.sosyoloji-toplumsal-yapi', name: 'Sosyoloji: Toplumsal Yapı' },
    { id: 'ayt.felsefe.sosyoloji-degisme', name: 'Sosyoloji: Toplumsal Değişme ve Gelişme' },
    { id: 'ayt.felsefe.sosyoloji-kultur', name: 'Sosyoloji: Toplum ve Kültür' },
    { id: 'ayt.felsefe.sosyoloji-kurumlar', name: 'Sosyoloji: Toplumsal Kurumlar' },
    { id: 'ayt.felsefe.mantik-giris', name: 'Mantık: Mantığa Giriş' },
    { id: 'ayt.felsefe.mantik-klasik', name: 'Mantık: Klasik Mantık' },
    { id: 'ayt.felsefe.mantik-dil', name: 'Mantık: Mantık ve Dil' },
    { id: 'ayt.felsefe.mantik-sembolik', name: 'Mantık: Sembolik Mantık' },
  ],
  din: [
    { id: 'ayt.din.dunya-ve-ahiret', name: 'Dünya ve Ahiret' },
    { id: 'ayt.din.kurana-gore-hz-muhammed', name: 'Kur’an’a Göre Hz. Muhammed' },
    { id: 'ayt.din.kuranda-kavramlar', name: 'Kur’an’da Bazı Kavramlar' },
    { id: 'ayt.din.inancla-ilgili-meseleler', name: 'İnançla İlgili Meseleler' },
    { id: 'ayt.din.yahudilik-hristiyanlik', name: 'Yahudilik ve Hristiyanlık' },
    { id: 'ayt.din.islam-ve-bilim', name: 'İslam ve Bilim' },
    { id: 'ayt.din.anadoluda-islam', name: 'Anadolu’da İslam' },
    { id: 'ayt.din.tasavvufi-yorumlar', name: 'İslam Düşüncesinde Tasavvufi Yorumlar' },
    { id: 'ayt.din.guncel-dini-meseleler', name: 'Güncel Dinî Meseleler' },
    { id: 'ayt.din.hint-cin-dinleri', name: 'Hint ve Çin Dinleri' },
  ],
  yabanci_dil: [
    { id: 'ayt.yabanci_dil.kelime-bilgisi', name: 'Kelime Bilgisi' },
    { id: 'ayt.yabanci_dil.dil-bilgisi', name: 'Dil Bilgisi (Gramer)' },
    { id: 'ayt.yabanci_dil.cloze-test', name: 'Cloze Test' },
    { id: 'ayt.yabanci_dil.cumle-tamamlama', name: 'Cümle Tamamlama' },
    { id: 'ayt.yabanci_dil.ceviri-yd-tr', name: 'Çeviri (Yabancı Dil → Türkçe)' },
    { id: 'ayt.yabanci_dil.ceviri-tr-yd', name: 'Çeviri (Türkçe → Yabancı Dil)' },
    { id: 'ayt.yabanci_dil.okudugunu-anlama', name: 'Okuduğunu Anlama (Paragraf Soruları)' },
    { id: 'ayt.yabanci_dil.diyalog-tamamlama', name: 'Diyalog Tamamlama' },
    { id: 'ayt.yabanci_dil.anlamca-yakin-cumle', name: 'Anlamca En Yakın Cümle' },
    { id: 'ayt.yabanci_dil.paragraf-tamamlama', name: 'Paragraf Tamamlama' },
    { id: 'ayt.yabanci_dil.anlam-butunlugu', name: 'Paragrafta Anlam Bütünlüğünü Bozan Cümle' },
  ],
};
