/*
 * YKS – TYT (Temel Yeterlilik Testi) konu listesi.
 *
 * Kaynaklar (erişim: 2026-10-04):
 * - ÖSYM YKS test yapısı (TYT: Türkçe 40, Temel Matematik 40, Sosyal Bilimler 20
 *   [Tarih 5, Coğrafya 5, Felsefe 5, Din 5], Fen 20 [Fizik 7, Kimya 7, Biyoloji 6]); dağılım aşağıdaki
 *   ikincil kaynaklardan alındı, ÖSYM kılavuzu doğrudan açılmadı: https://www.osym.gov.tr/
 * - MEB OGM, 2026-2027 Türkiye Yüzyılı Maarif Modeli geçişi ("hazırlık, 9, 10 ve 11. sınıflarda
 *   uygulanacak ... 12. sınıfta ise önceki öğretim programları uygulanmaya devam edecektir"):
 *   https://ogm.meb.gov.tr/www/2026-2027-egitim-ogretim-yili-turkiye-yuzyili-maarif-modeli-taslak-cerceve-planlar-yayimlandi/icerik/2633/tr
 * - Yaygın konu listeleri (karşılaştırma için):
 *   https://www.milliyet.com.tr/egitim/tyt-konulari-2026-tyt-matematik-turkce-biyoloji-fizik-cografya-kimya-tarih-konulari-ve-dagilimi-6609047
 *   https://www.atlasrehberlik.com/tyt-konulari-ve-soru-dagilimi/
 *   https://unikazan.com/blog/tyt-matematik-2026-konulari/
 *   https://unikazan.com/blog/turkiye-yuzyili-maarif-modeli-yksyi-nasil-etkileyecek/
 *
 * Belirsizlik notu: YKS 2027 adayları (2026-2027'de 12. sınıf) 9-12. sınıfı önceki (2018 tabanlı)
 * programlarla okudu; liste bu programa göredir. Maarif Modeli'ne göre hazırlanan ilk YKS'nin 2028
 * olması bekleniyor; o yıl konu adları/kapsamı değişebilir (yeni id'ler eklenir, eskiler silinmez).
 * TYT Sosyal ve Fen listeleri 9-10. sınıf ünitelerini (Felsefe yalnız 10. sınıf) izler; bazı
 * kaynaklar Din Kültürü için 11. sınıf ünitelerini de TYT kapsamında sayar.
 * Yayınevlerine göre konu bölme düzeyi farklıdır; burada konu takip çizelgesi düzeyi esas alındı.
 */
import type { SubjectTopics } from './types';

export const TYT_TOPICS: SubjectTopics = {
  turkce: [
    { id: 'tyt.turkce.sozcukte-anlam', name: 'Sözcükte Anlam' },
    { id: 'tyt.turkce.soz-yorumu', name: 'Söz Yorumu' },
    { id: 'tyt.turkce.cumlede-anlam', name: 'Cümlede Anlam' },
    { id: 'tyt.turkce.paragrafta-anlam', name: 'Paragrafta Anlam' },
    { id: 'tyt.turkce.paragrafta-yapi', name: 'Paragrafta Yapı ve Anlatım Teknikleri' },
    { id: 'tyt.turkce.ses-bilgisi', name: 'Ses Bilgisi' },
    { id: 'tyt.turkce.yazim-kurallari', name: 'Yazım Kuralları' },
    { id: 'tyt.turkce.noktalama', name: 'Noktalama İşaretleri' },
    { id: 'tyt.turkce.sozcukte-yapi', name: 'Sözcükte Yapı (Kök, Ek, Gövde)' },
    { id: 'tyt.turkce.isimler', name: 'İsimler' },
    { id: 'tyt.turkce.sifatlar', name: 'Sıfatlar' },
    { id: 'tyt.turkce.zamirler', name: 'Zamirler' },
    { id: 'tyt.turkce.zarflar', name: 'Zarflar' },
    { id: 'tyt.turkce.edat-baglac-unlem', name: 'Edat, Bağlaç, Ünlem' },
    { id: 'tyt.turkce.fiiller', name: 'Fiiller (Kip, Kişi, Ek Fiil)' },
    { id: 'tyt.turkce.fiilimsiler', name: 'Fiilimsiler' },
    { id: 'tyt.turkce.fiilde-cati', name: 'Fiilde Çatı' },
    { id: 'tyt.turkce.cumlenin-ogeleri', name: 'Cümlenin Ögeleri' },
    { id: 'tyt.turkce.cumle-turleri', name: 'Cümle Türleri' },
    { id: 'tyt.turkce.anlatim-bozukluklari', name: 'Anlatım Bozuklukları' },
  ],
  matematik: [
    { id: 'tyt.matematik.temel-kavramlar', name: 'Temel Kavramlar' },
    { id: 'tyt.matematik.sayi-basamaklari', name: 'Sayı Basamakları' },
    { id: 'tyt.matematik.bolme-bolunebilme', name: 'Bölme ve Bölünebilme' },
    { id: 'tyt.matematik.ebob-ekok', name: 'EBOB – EKOK' },
    { id: 'tyt.matematik.rasyonel-sayilar', name: 'Rasyonel Sayılar' },
    { id: 'tyt.matematik.ondalik-sayilar', name: 'Ondalık Sayılar' },
    { id: 'tyt.matematik.basit-esitsizlikler', name: 'Basit Eşitsizlikler' },
    { id: 'tyt.matematik.mutlak-deger', name: 'Mutlak Değer' },
    { id: 'tyt.matematik.uslu-sayilar', name: 'Üslü Sayılar' },
    { id: 'tyt.matematik.koklu-sayilar', name: 'Köklü Sayılar' },
    { id: 'tyt.matematik.carpanlara-ayirma', name: 'Çarpanlara Ayırma' },
    { id: 'tyt.matematik.oran-oranti', name: 'Oran – Orantı' },
    { id: 'tyt.matematik.denklem-cozme', name: 'Denklem Çözme' },
    { id: 'tyt.matematik.sayi-problemleri', name: 'Sayı Problemleri' },
    { id: 'tyt.matematik.kesir-problemleri', name: 'Kesir Problemleri' },
    { id: 'tyt.matematik.yas-problemleri', name: 'Yaş Problemleri' },
    { id: 'tyt.matematik.isci-problemleri', name: 'İşçi Problemleri' },
    { id: 'tyt.matematik.yuzde-problemleri', name: 'Yüzde Problemleri' },
    { id: 'tyt.matematik.kar-zarar-problemleri', name: 'Kâr – Zarar Problemleri' },
    { id: 'tyt.matematik.karisim-problemleri', name: 'Karışım Problemleri' },
    { id: 'tyt.matematik.hareket-problemleri', name: 'Hareket Problemleri' },
    { id: 'tyt.matematik.grafik-problemleri', name: 'Grafik Problemleri' },
    { id: 'tyt.matematik.rutin-olmayan-problemler', name: 'Rutin Olmayan Problemler' },
    { id: 'tyt.matematik.mantik', name: 'Mantık' },
    { id: 'tyt.matematik.kumeler', name: 'Kümeler' },
    { id: 'tyt.matematik.kartezyen-carpim', name: 'Kartezyen Çarpım' },
    { id: 'tyt.matematik.fonksiyonlar', name: 'Fonksiyonlar' },
    { id: 'tyt.matematik.polinomlar', name: 'Polinomlar' },
    { id: 'tyt.matematik.ikinci-derece-denklemler', name: '2. Dereceden Denklemler' },
    { id: 'tyt.matematik.permutasyon', name: 'Permütasyon' },
    { id: 'tyt.matematik.kombinasyon', name: 'Kombinasyon' },
    { id: 'tyt.matematik.binom', name: 'Binom' },
    { id: 'tyt.matematik.olasilik', name: 'Olasılık' },
    { id: 'tyt.matematik.veri-istatistik', name: 'Veri – İstatistik' },
  ],
  geometri: [
    { id: 'tyt.geometri.dogruda-ucgende-acilar', name: 'Doğruda ve Üçgende Açılar' },
    { id: 'tyt.geometri.dik-ucgen', name: 'Dik Üçgen ve Pisagor' },
    { id: 'tyt.geometri.ozel-ucgenler', name: 'Özel Üçgenler' },
    { id: 'tyt.geometri.ikizkenar-eskenar-ucgen', name: 'İkizkenar ve Eşkenar Üçgen' },
    { id: 'tyt.geometri.aciortay', name: 'Açıortay' },
    { id: 'tyt.geometri.kenarortay', name: 'Kenarortay' },
    { id: 'tyt.geometri.ucgende-eslik-benzerlik', name: 'Üçgende Eşlik ve Benzerlik' },
    { id: 'tyt.geometri.aci-kenar-bagintilari', name: 'Üçgende Açı – Kenar Bağıntıları' },
    { id: 'tyt.geometri.ucgende-alan', name: 'Üçgende Alan' },
    { id: 'tyt.geometri.cokgenler', name: 'Çokgenler' },
    { id: 'tyt.geometri.dortgenler', name: 'Dörtgenler' },
    { id: 'tyt.geometri.yamuk', name: 'Yamuk' },
    { id: 'tyt.geometri.paralelkenar', name: 'Paralelkenar' },
    { id: 'tyt.geometri.eskenar-dortgen-deltoid', name: 'Eşkenar Dörtgen ve Deltoid' },
    { id: 'tyt.geometri.dikdortgen-kare', name: 'Dikdörtgen ve Kare' },
    { id: 'tyt.geometri.cemberde-aci', name: 'Çemberde Açı' },
    { id: 'tyt.geometri.cemberde-uzunluk', name: 'Çemberde Uzunluk' },
    { id: 'tyt.geometri.dairede-alan', name: 'Daire ve Dairede Alan' },
    { id: 'tyt.geometri.analitik-geometri', name: 'Noktanın ve Doğrunun Analitiği' },
    { id: 'tyt.geometri.kati-cisimler', name: 'Katı Cisimler' },
  ],
  fizik: [
    { id: 'tyt.fizik.fizik-bilimine-giris', name: 'Fizik Bilimine Giriş' },
    { id: 'tyt.fizik.madde-ve-ozellikleri', name: 'Madde ve Özellikleri' },
    { id: 'tyt.fizik.basinc', name: 'Basınç' },
    { id: 'tyt.fizik.kaldirma-kuvveti', name: 'Kaldırma Kuvveti' },
    { id: 'tyt.fizik.isi-sicaklik-genlesme', name: 'Isı, Sıcaklık ve Genleşme' },
    { id: 'tyt.fizik.hareket', name: 'Hareket' },
    { id: 'tyt.fizik.kuvvet-newton', name: 'Kuvvet ve Newton’un Hareket Yasaları' },
    { id: 'tyt.fizik.is-guc-enerji', name: 'İş, Güç ve Enerji' },
    { id: 'tyt.fizik.elektrostatik', name: 'Elektrostatik' },
    { id: 'tyt.fizik.elektrik-akimi', name: 'Elektrik Akımı ve Devreler' },
    { id: 'tyt.fizik.manyetizma', name: 'Manyetizma' },
    { id: 'tyt.fizik.dalgalar', name: 'Dalgalar' },
    { id: 'tyt.fizik.aydinlanma-golge', name: 'Aydınlanma ve Gölge' },
    { id: 'tyt.fizik.aynalar', name: 'Düzlem ve Küresel Aynalar' },
    { id: 'tyt.fizik.kirilma-mercekler', name: 'Kırılma, Mercekler ve Renkler' },
  ],
  kimya: [
    { id: 'tyt.kimya.kimya-bilimi', name: 'Kimya Bilimi' },
    { id: 'tyt.kimya.atom-periyodik-sistem', name: 'Atom ve Periyodik Sistem' },
    { id: 'tyt.kimya.kimyasal-turler-etkilesim', name: 'Kimyasal Türler Arası Etkileşimler' },
    { id: 'tyt.kimya.maddenin-halleri', name: 'Maddenin Halleri' },
    { id: 'tyt.kimya.doga-ve-kimya', name: 'Doğa ve Kimya' },
    { id: 'tyt.kimya.temel-kanunlar', name: 'Kimyanın Temel Kanunları' },
    { id: 'tyt.kimya.kimyasal-hesaplamalar', name: 'Mol Kavramı ve Kimyasal Hesaplamalar' },
    { id: 'tyt.kimya.kimyasal-tepkimeler', name: 'Kimyasal Tepkimeler' },
    { id: 'tyt.kimya.karisimlar', name: 'Karışımlar' },
    { id: 'tyt.kimya.asit-baz-tuz', name: 'Asitler, Bazlar ve Tuzlar' },
    { id: 'tyt.kimya.kimya-her-yerde', name: 'Kimya Her Yerde' },
  ],
  biyoloji: [
    { id: 'tyt.biyoloji.canlilarin-ortak-ozellikleri', name: 'Canlıların Ortak Özellikleri' },
    { id: 'tyt.biyoloji.inorganik-bilesikler', name: 'Canlıların Temel Bileşenleri: İnorganik Bileşikler' },
    { id: 'tyt.biyoloji.organik-bilesikler', name: 'Canlıların Temel Bileşenleri: Organik Bileşikler' },
    { id: 'tyt.biyoloji.hucre-organeller', name: 'Hücre ve Organeller' },
    { id: 'tyt.biyoloji.madde-gecisleri', name: 'Hücre Zarından Madde Geçişi' },
    { id: 'tyt.biyoloji.siniflandirma', name: 'Canlıların Sınıflandırılması' },
    { id: 'tyt.biyoloji.mitoz-eseysiz-ureme', name: 'Mitoz ve Eşeysiz Üreme' },
    { id: 'tyt.biyoloji.mayoz-eseyli-ureme', name: 'Mayoz ve Eşeyli Üreme' },
    { id: 'tyt.biyoloji.kalitim', name: 'Kalıtım' },
    { id: 'tyt.biyoloji.ekosistem-ekolojisi', name: 'Ekosistem Ekolojisi' },
    { id: 'tyt.biyoloji.cevre-sorunlari', name: 'Güncel Çevre Sorunları' },
  ],
  tarih: [
    { id: 'tyt.tarih.tarih-ve-zaman', name: 'Tarih ve Zaman' },
    { id: 'tyt.tarih.insanligin-ilk-donemleri', name: 'İnsanlığın İlk Dönemleri' },
    { id: 'tyt.tarih.orta-cagda-dunya', name: 'Orta Çağ’da Dünya' },
    { id: 'tyt.tarih.ilk-orta-cag-turk-dunyasi', name: 'İlk ve Orta Çağlarda Türk Dünyası' },
    { id: 'tyt.tarih.islam-medeniyeti', name: 'İslam Medeniyetinin Doğuşu' },
    { id: 'tyt.tarih.ilk-turk-islam-devletleri', name: 'Türklerin İslamiyet’i Kabulü ve İlk Türk-İslam Devletleri' },
    { id: 'tyt.tarih.selcuklu-turkiyesi', name: 'Yerleşme ve Devletleşme Sürecinde Selçuklu Türkiyesi' },
    { id: 'tyt.tarih.beylikten-devlete-osmanli', name: 'Beylikten Devlete Osmanlı (1302-1453)' },
    { id: 'tyt.tarih.dunya-gucu-osmanli', name: 'Dünya Gücü Osmanlı (1453-1595)' },
    { id: 'tyt.tarih.osmanli-kultur-medeniyet', name: 'Osmanlı Kültür ve Medeniyeti' },
    { id: 'tyt.tarih.arayis-yillari', name: 'Arayış Yılları (17. Yüzyıl)' },
    { id: 'tyt.tarih.diplomasi-ve-degisim', name: 'Avrupa ve Osmanlı: Diplomasi ve Değişim (18. Yüzyıl)' },
    { id: 'tyt.tarih.en-uzun-yuzyil', name: 'En Uzun Yüzyıl (1800-1922)' },
    { id: 'tyt.tarih.yirminci-yuzyil-osmanli', name: '20. Yüzyıl Başlarında Osmanlı Devleti ve Dünya' },
    { id: 'tyt.tarih.milli-mucadele', name: 'Millî Mücadele' },
    { id: 'tyt.tarih.ataturk-ilke-inkilaplari', name: 'Atatürkçülük ve Türk İnkılabı' },
    { id: 'tyt.tarih.ataturk-donemi-dis-politika', name: 'Atatürk Dönemi Türk Dış Politikası' },
  ],
  cografya: [
    { id: 'tyt.cografya.doga-ve-insan', name: 'Doğa ve İnsan' },
    { id: 'tyt.cografya.dunyanin-sekli-hareketleri', name: 'Dünya’nın Şekli ve Hareketleri' },
    { id: 'tyt.cografya.cografi-konum', name: 'Coğrafi Konum' },
    { id: 'tyt.cografya.harita-bilgisi', name: 'Harita Bilgisi' },
    { id: 'tyt.cografya.atmosfer-sicaklik', name: 'Atmosfer ve Sıcaklık' },
    { id: 'tyt.cografya.basinc-ruzgarlar', name: 'Basınç ve Rüzgârlar' },
    { id: 'tyt.cografya.nem-yagis', name: 'Nem, Yağış ve Buharlaşma' },
    { id: 'tyt.cografya.iklim-tipleri', name: 'İklim Tipleri' },
    { id: 'tyt.cografya.yerin-yapisi', name: 'Yerin Yapısı ve İç Kuvvetler' },
    { id: 'tyt.cografya.dis-kuvvetler', name: 'Dış Kuvvetler' },
    { id: 'tyt.cografya.su-toprak-bitki', name: 'Su, Toprak ve Bitki Örtüsü' },
    { id: 'tyt.cografya.turkiyenin-yer-sekilleri', name: 'Türkiye’nin Yer Şekilleri' },
    { id: 'tyt.cografya.nufus', name: 'Nüfus' },
    { id: 'tyt.cografya.goc', name: 'Göç' },
    { id: 'tyt.cografya.yerlesme', name: 'Yerleşme' },
    { id: 'tyt.cografya.ekonomik-faaliyetler', name: 'Ekonomik Faaliyetler' },
    { id: 'tyt.cografya.bolgeler', name: 'Bölgeler' },
    { id: 'tyt.cografya.ulasim-hatlari', name: 'Uluslararası Ulaşım Hatları' },
    { id: 'tyt.cografya.dogal-afetler', name: 'Çevre ve Toplum: Doğal Afetler' },
  ],
  felsefe: [
    { id: 'tyt.felsefe.felsefeyi-tanima', name: 'Felsefeyi Tanıma' },
    { id: 'tyt.felsefe.felsefe-ile-dusunme', name: 'Felsefe ile Düşünme' },
    { id: 'tyt.felsefe.varlik-felsefesi', name: 'Varlık Felsefesi' },
    { id: 'tyt.felsefe.bilgi-felsefesi', name: 'Bilgi Felsefesi' },
    { id: 'tyt.felsefe.bilim-felsefesi', name: 'Bilim Felsefesi' },
    { id: 'tyt.felsefe.ahlak-felsefesi', name: 'Ahlak Felsefesi' },
    { id: 'tyt.felsefe.din-felsefesi', name: 'Din Felsefesi' },
    { id: 'tyt.felsefe.siyaset-felsefesi', name: 'Siyaset Felsefesi' },
    { id: 'tyt.felsefe.sanat-felsefesi', name: 'Sanat Felsefesi' },
  ],
  din: [
    { id: 'tyt.din.bilgi-ve-inanc', name: 'Bilgi ve İnanç' },
    { id: 'tyt.din.din-ve-islam', name: 'Din ve İslam' },
    { id: 'tyt.din.islam-ve-ibadet', name: 'İslam ve İbadet' },
    { id: 'tyt.din.genclik-ve-degerler', name: 'Gençlik ve Değerler' },
    { id: 'tyt.din.gonul-cografyamiz', name: 'Gönül Coğrafyamız' },
    { id: 'tyt.din.allah-insan-iliskisi', name: 'Allah İnsan İlişkisi' },
    { id: 'tyt.din.hz-muhammed', name: 'Hz. Muhammed (s.a.v.)' },
    { id: 'tyt.din.vahiy-ve-akil', name: 'Vahiy ve Akıl Kur’an Yorumları' },
    { id: 'tyt.din.islam-dusuncesinde-yorumlar', name: 'İslam Düşüncesinde Yorumlar, Mezhepler' },
    { id: 'tyt.din.din-kultur-medeniyet', name: 'Din, Kültür ve Medeniyet' },
  ],
};
